apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx-container
        image: mywebpage
        ports:
        - containerPort: 80
        env:
        - name: STUDENT_NAME
          value: "shebin" 
        - name: NGINX_ENVSUBST_OUTPUT_DIR # Add this!
          value: "/usr/share/nginx/html"